### ISSUE TITLE
can't install on node 6

### ISSUE THREAD

**Issue by macrozone** [Preposterous/exp-deploy-cli#11]
it expects a node version >= 8. Is this really needed?

**Comment by peterpme** [comment]
Hey @macrozone,

sorry not getting notifications for some reason.

Yes, because we're using `async / await`. If you'd like to convert to promises I'm open to a PR 😄 

Also, you can just use `nvm` and run: ```nvm install 8``` because there's no reason why you can't run your native app on Node 8
