### ISSUE TITLE
explain how "config" in app.json work

### ISSUE THREAD

**Issue by macrozone** [Preposterous/exp-deploy-cli#12]
In the readme it states:

"if you'd like to store environment variables, create a config object next to expo within app.json:"

but in the code seems no support for that and also expo does not mention that neither.

So, does this really work?

**Comment by eliasturbay** [comment]
Hey @peterpme I was trying to use it as well, and the problem I'm having is that I can't find a way to retrieve those values from the `config` section...
I tried to use something like:
`Expo.Constants.manifest.config.apiBaseUrl` but it didn't worked 🤔 

What am I doing wrong here? 
Thanks in advance!

**Comment by peterpme** [comment]
Hey @macrozone and @eliasturbay,
Sorry I'm not sure why notifications aren't coming to my email!

Here's what I do:

```
{
  "config": {
     apiUrl: "google.com/api",
     sentryApiKey: "xyz"
  },
  "expo": {
      name: "my-app-name",
      slug: "my-app-slug"
  }
}
```

Expo won't read your variables via `Expo.Constants.manifest.config`. You have to import the json file on your own:


```
import App from 'app.json'

const API_URL = App.config.apiUrl

```

Does that make sense?

I will update the readme with this insight

**Comment by peterpme** [comment]
https://github.com/Preposterous/exp-deploy-cli/blob/master/README.md#using-config-variables-in-your-app

I added this to the README. If you both have better suggestions please let me know!

**Comment by eliasturbay** [comment]
Thank you very much Peter! That makes sense to me 🙂
