### ISSUE TITLE
expo-deploy command issue

### ISSUE THREAD

**Issue by RyszardRzepa** [Preposterous/exp-deploy-cli#9]
After installing expo-deploy cli and building config/exp-production.json, /config/exp-development.json, running command "exp-deploy --env production" will prompt same in terminal as command "exp-deploy --help". 

Running command  "exp-deploy --env staging" will show: "app.json and/or config don't exist. Are you sure you're in the right directory? Did you run [exp-deploy config] first?"
Note: I am running this command from root direcotry where is app.json and config/

**Comment by peterpme** [comment]
Hey @RyszardRzepa sorry for the delay!

Oops, I will push a fix for this :)

**Comment by peterpme** [comment]
Hey @RyszardRzepa,

Sorry, in the documentation I said `development`, (but it actually wanted staging).

I've removed the limitation so you can pass in any env that you want as long as there's a matching `config/exp-${env}.json` file for it.

1.5.0 has the updated fix!
